defaults: &defaults
  secret_key_base: secret_key_base_for_staging_tries_to_be_a_bit_longer_than_before_just_to_make_sure_its_useful_12_@1
  
  s3:                                                                              
    aws_access_key_id: ____c                                                       
    aws_secret_access_key: ____                                                    
    attachments_bucket: production

  ses:
    access_key: some_access_key
    secret: some_secret

  mysql:
    username: 'bd103842d9ad0a'
    password: '47d8fdb6' 
    host: 'us-cdbr-east-02.cleardb.com/heroku_0f85f9282fa4bcd?reconnect=true'
    port: 3306

  exception_recipients: "some@me.com,other@me.com"

  regularities:
    low:
      funding_amount: 2500
      funding_count: 3 
    high:
      funding_amount: 10000
      funding_count: 10
  
  lock_issues:
    expiration_interval_minutes: 15
  
  redis:
    cache_url: 'redis://:p35d7b0ae3eea6ba4495d45cd4b5e549436905651039737539db7415b3192921f@ec2-3-224-193-62.compute-1.amazonaws.com:22519'
    namespace: 'compliance'
    pool_size: 8

production:
  <<: *defaults

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults